name: student-enrollment-system

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile

    image: student-enrollment-api:local
    container_name: student_enrollment_api
    restart: unless-stopped
    init: true

    environment:
      APP_ENV: docker
      APP_PORT: 8081
      HTTP_READ_TIMEOUT: 10s
      HTTP_WRITE_TIMEOUT: 10s
      HTTP_IDLE_TIMEOUT: 60s
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable

    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

    ports:
      - "8081:8081"

    networks:
      - student_network

  migrate:
    image: postgres:16-alpine
    container_name: student_enrollment_migrate
    restart: "no"

    environment:
      PGPASSWORD: ${POSTGRES_PASSWORD}

    depends_on:
      postgres:
        condition: service_healthy

    volumes:
      - ./migrations:/migrations:ro

    command:
      - /bin/sh
      - -c
      - >
        psql
        --host=postgres
        --username=${POSTGRES_USER}
        --dbname=${POSTGRES_DB}
        --set=ON_ERROR_STOP=1
        --file=/migrations/000001_create_students.up.sql

    networks:
      - student_network

  postgres:
    image: postgres:16-alpine
    container_name: student_enrollment_postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "${POSTGRES_HOST_PORT:-5433}:5432"

    volumes:
      - student_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

    networks:
      - student_network

  adminer:
    image: adminer:4
    container_name: student_enrollment_adminer
    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "18080:8080"

    networks:
      - student_network

volumes:
  student_postgres_data:
    name: student_enrollment_postgres_data

networks:
  student_network:
    name: student_enrollment_network