# Generated by Django 5.2.17 on 2026-10-08 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'مدیر سیستم'), ('education_staff', 'کارشناس آموزش'), ('instructor', 'استاد'), ('student', 'دانشجو')], db_index=True, default='student', max_length=32, verbose_name='نقش')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='شماره تماس')),
                ('national_code', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='کد ملی')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='accounts/avatars/%Y/%m/', verbose_name='تصویر پروفایل')),
                ('bio', models.TextField(blank=True, verbose_name='درباره کاربر')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تأیید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل کاربر',
                'verbose_name_plural': 'پروفایل\u200cهای کاربران',
                'ordering': ('user__first_name', 'user__last_name', 'user__username'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('national_code', ''), _negated=True), fields=('national_code',), name='accounts_unique_nonempty_national_code')],
            },
        ),
    ]
