# Generated by Django 5.2.17 on 2026-10-07 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='شناسه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('accent_color', models.CharField(default='#6D5DFB', max_length=20, verbose_name='رنگ شاخص')),
                ('icon_name', models.CharField(blank=True, max_length=60, verbose_name='نام آیکن')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InstructorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_instructor_id', models.PositiveBigIntegerField(blank=True, null=True, unique=True, verbose_name='شناسه استاد در Go API')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='شناسه')),
                ('bio', models.TextField(blank=True, verbose_name='درباره استاد')),
                ('expertise', models.CharField(blank=True, max_length=300, verbose_name='تخصص')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='شماره تماس')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='آدرس تصویر')),
                ('source_url', models.URLField(blank=True, max_length=500, verbose_name='منبع اطلاعات')),
                ('is_featured', models.BooleanField(default=False, verbose_name='استاد منتخب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
            ],
            options={
                'verbose_name': 'استاد',
                'verbose_name_plural': 'استادان',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='CourseCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_course_id', models.PositiveBigIntegerField(blank=True, null=True, unique=True, verbose_name='شناسه دوره در Go API')),
                ('title', models.CharField(max_length=220, verbose_name='عنوان دوره')),
                ('slug', models.SlugField(max_length=240, unique=True, verbose_name='شناسه')),
                ('short_description', models.CharField(blank=True, max_length=350, verbose_name='توضیح کوتاه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات کامل')),
                ('price_toman', models.PositiveBigIntegerField(default=0, verbose_name='قیمت به تومان')),
                ('duration_hours', models.PositiveIntegerField(default=0, verbose_name='مدت دوره به ساعت')),
                ('level', models.CharField(choices=[('beginner', 'مقدماتی'), ('intermediate', 'متوسط'), ('advanced', 'پیشرفته'), ('all_levels', 'مناسب همه سطوح')], default='all_levels', max_length=20, verbose_name='سطح دوره')),
                ('prerequisites', models.TextField(blank=True, verbose_name='پیش\u200cنیازها')),
                ('cover_image_url', models.URLField(blank=True, max_length=500, verbose_name='تصویر دوره')),
                ('source_url', models.URLField(blank=True, max_length=500, verbose_name='صفحه رسمی دوره')),
                ('is_featured', models.BooleanField(default=False, verbose_name='دوره منتخب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('source_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان بررسی منبع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='catalog.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'دوره',
                'verbose_name_plural': 'دوره\u200cها',
                'ordering': ['-is_featured', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_text', models.CharField(blank=True, max_length=120, verbose_name='تاریخ شروع')),
                ('schedule_text', models.CharField(blank=True, max_length=200, verbose_name='برنامه برگزاری')),
                ('delivery_mode', models.CharField(choices=[('in_person', 'حضوری'), ('online', 'آنلاین'), ('hybrid', 'حضوری و آنلاین')], default='in_person', max_length=20, verbose_name='نوع برگزاری')),
                ('status', models.CharField(choices=[('upcoming', 'به\u200cزودی'), ('open', 'در حال ثبت\u200cنام'), ('closed', 'تکمیل ظرفیت'), ('finished', 'پایان\u200cیافته')], default='upcoming', max_length=20, verbose_name='وضعیت')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='ظرفیت')),
                ('price_override_toman', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت اختصاصی این کلاس')),
                ('registration_url', models.URLField(blank=True, max_length=500, verbose_name='لینک ثبت\u200cنام')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='catalog.coursecatalog', verbose_name='دوره')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='catalog.instructorprofile', verbose_name='استاد')),
            ],
            options={
                'verbose_name': 'کلاس در حال برگزاری',
                'verbose_name_plural': 'کلاس\u200cهای در حال برگزاری',
                'ordering': ['status', 'course__title'],
                'constraints': [models.UniqueConstraint(fields=('course', 'instructor', 'start_date_text', 'schedule_text'), name='unique_catalog_course_offering')],
            },
        ),
    ]
